var Zef=window.Zef||{};Zef.VisualRegistry=function(){this.componentRegistry=new Map};Zef.VisualRegistry.prototype.addVisual=function(a,b){this.componentRegistry.put(a,b)};Zef.VisualRegistry.prototype.getVisual=function(a,b){!1===this.populated&&this.populate();var c=null;"undefined"!==typeof a&&(c=this.componentRegistry.get(a));null==c&&"undefined"!==typeof b&&(c=this.componentRegistry.get(b));return c};Zef._globalVisualRegistry=new Zef.VisualRegistry;
Zef.Component=function(){this.name="undefined";this.category="genericComponent";this.id="undefined";this.disableReDraw=this.uiDone=!1;this.components=new Map;this.hasVisual=!0;this.visual=null;this.properties={};this.player=null;this.loadContent=!0;this.parentComponent=null;this.questionAnswered=!1;this.canShow=!0};Zef.Component.prototype.init=function(){};Zef.Component.prototype.loadDone=function(){};
Zef.Component.prototype.getRepliesByQuestion=function(a){if("undefined"!=typeof a.repliesByQuestion)return a.repliesByQuestion;if("undefined"!==typeof a.replies){a.repliesByQuestion={};for(var b=0;b<a.replies.length;b++)if("function"!=typeof a.replies[b]){var c=a.replies[b];c&&(a.repliesByQuestion[c.q]=c)}return a.repliesByQuestion}};
Zef.Component.prototype.load=function(){if(!0===this.loadContent){var a=this;Zef.loadFromServer(this.name,{m:"data",id:this.id},function(b){a.handleComponents(b)},function(){},function(){a.loadDone()})}};Zef.Component.prototype.show=function(){this.canShow=!0;this.rebuildUi()};Zef.Component.prototype.hide=function(){this.unbuildVisual()};Zef.Component.prototype.componentLoaded=function(){};
Zef.Component.prototype.componentsLoaded=function(){this.componentLoadDone=!0;setTimeout("Zef.executeUiComponentCallQueue()",5)};
Zef.Component.prototype.setData=function(a){this.properties=a.properties;"undefined"!==typeof a.uiData&&(this.uiData=a.uiData);"undefined"===this.id&&"undefined"!==typeof a.id?this.id=a.id:"undefined"===this.id&&("undefined"!==typeof this.properties&&"undefined"!==typeof this.properties.id)&&(this.id=this.properties.id);"undefined"!==typeof a.properties&&null!=a.properties.tags&&this.addTags(a.properties.tags);"undefined"!==typeof a.properties&&"undefined"!==typeof a.properties.componentName?this.componentName=
a.properties.componentName:"undefined"!==typeof a.name&&(this.componentName=a.name);this.applyI18n()};
Zef.Component.prototype.applyI18n=function(){if(Zef._locales&&(this.player&&Zef._lang)&&Zef._locales[this.player.id]){var a=null;Zef._locales[this.player.id][Zef._lang]?a=Zef._locales[this.player.id][Zef._lang]:Zef._locales[this.player.id].en&&(a=Zef._locales[this.player.id].en);if(a)for(var b in this.properties){var c=this.name+"_"+this.properties.id+"_"+b;a[c]&&(this.properties[b]=a[c]);if("customProperties"===b)for(var d in this.properties[b]){var f=this.properties[b][d],c=this.name+"_"+this.properties.id+
"_"+b+"_"+f.name;a[c]&&(f.value=a[c])}else if("replies"===b)for(var e in this.properties[b])for(sidx in f=this.properties[b][e],f)if(c=this.name+"_"+f.answererId+"_"+sidx,a[c]&&(f[sidx]=a[c]),"customProperties"===sidx)for(var g in f[sidx]){var c=f[sidx][g],h=this.name+"_"+f.answererId+"_"+sidx+"_"+c.name;a[h]&&(c.value=a[h])}}}};
Zef.Component.prototype.addTags=function(a){if("undefined"==typeof this.tags||null==this.tags)this.tags=[];if("undefined"!==typeof a&&null!=a)for(var b in a)"function"!=typeof a[b]&&(this.tags[this.tags.length]=a[b])};
Zef.Component.prototype.handleComponents=function(a){if("undefined"!==typeof a){this.setData(a);if("undefined"!==typeof a.visuals)for(var b in a.visuals){var c=a.visuals[b];"function"!==typeof c&&Zef._globalVisualRegistry.addVisual(c.compName,c.visual)}for(var d in a.components)b=a.components[d],"function"!==typeof b&&(c=eval("new "+b.cclass+"()"),"undefined"!==typeof b.id&&(c.id=b.id),Zef.log(""+this.name+" "+this.properties.id+" adding component "+b.name+" "+b.id),this.components.put(b.name,c),
c.indexInParent=parseInt(d)+1,c.parentComponent=this,c.player=this.player,c.init(),"undefined"!==typeof b.data?c.handleComponents(b.data):c.load(),this.componentLoaded(c))}this.componentsLoaded()};
Zef.Component.prototype.buildUi=function(){if(!1!==this.hasVisual)if("undefined"===typeof this.componentLoadDone||!1==this.componentLoadDone)Zef._ZefUiComponentCallQueue.push([this,"buildUi"]);else if(!1===this.uiDone){if("undefined"===typeof this.uiData)this.uiData="undefined"!==typeof this.componentName?Zef._globalVisualRegistry.getVisual(this.componentName,this.name):Zef._globalVisualRegistry.getVisual(this.name);else if("undefined"===typeof this.uiData.visual){var a=null,a="undefined"!==typeof this.componentName?
Zef._globalVisualRegistry.getVisual(this.componentName,this.name):Zef._globalVisualRegistry.getVisual(this.name);"undefined"!==typeof a&&(this.uiData.visual=a.visual,this.uiData.htmlSrc=a.htmlSrc,this.uiData.cssSrc=a.cssSrc,"undefined"!==typeof a.scriptSrc&&(this.uiData.scriptSrc=a.scriptSrc))}"undefined"!==typeof this.uiData&&(!1===this.canShow?this.loadedUiData=this.uiData:this.buildVisual(this.uiData))}};Zef.Component.prototype.getChildComponents=function(){return this.components};
Zef.Component.prototype.unbuildVisual=function(){!1!==this.hasVisual&&("undefined"!==typeof this.visual&&null!=this.visual&&this.visual.removeUiElement(),this.uiDone=!1,this.getChildComponents().each(function(a,b){b.unbuildVisual()}),this.visual=null)};Zef.Component.prototype.rebuildUi=function(){!1!==this.hasVisual&&(this.unbuildVisual(),this.buildVisual(this.loadedUiData))};
Zef.Component.prototype.buildVisual=function(a){!1!==this.hasVisual&&(a&&(this.loadedUiData=a,null==this.visual&&(this.visual=eval("new "+a.visual+"()")),"undefined"!==typeof this.properties&&(null!=this.properties&&"undefined"!==typeof this.properties.o)&&(this.visual.order=this.properties.o),this.visual.component=this,this.visual.setData(a),"undefined"===typeof this.parentComponent||"undefined"===typeof this.parentComponent.visual?Zef._ZefUiComponentCallQueue.push([this,"buildVisual",a]):this.visual.addUiElement(),
this.visual&&this.visual.setAnswered(this.questionAnswered)),this.getChildComponents().each(function(a,c){c.uiDone=!1;c.buildUi()}),"function"==typeof this.buildDoneCb&&(a=this.buildDoneCb,this.buildDoneCb=null,a()))};Zef.Component.prototype.inputValueChanged=function(){};Zef.Component.prototype.itemSelected=function(){};Zef.Component.prototype.recalculate=function(){};Zef.Component.prototype.needsRebuildOnInputChange=function(){return!0};
Zef.Component.prototype.handleInputValueChanged=function(a,b,c){this.inputValueChanged(a,b,c);"undefined"!==typeof this.visual&&null!=this.visual&&this.visual.inputValueChanged(a,b,c);this.components.each(function(d,f){f.handleInputValueChanged(a,b,c)});c==this&&this.needsRebuildOnInputChange()&&this.rebuildUi()};Zef.Component.prototype.handleItemSelected=function(a,b,c){this.itemSelected(a,b,c);this.components.each(function(d,f){f.handleItemSelected(a,b,c)})};
Zef.Component.prototype.handleRecalculate=function(){this.recalculate();this.components.each(function(a,b){b.handleRecalculate()})};Zef.Visual=function(){this.scriptSrc=this.cssSrc=this.htmlSrc="";this.settings=this.component=this.element=null;this.containerClassName="children";this.order=1;this.useContainerClassName=!0;this.addParentIdToComponentId=this.clearContainer=this.skipStyle=this.skipOrder=this.questionAnswered=!1};
Zef.Visual.prototype.setData=function(a){this.settings=a.settings;this.htmlSrc=a.htmlSrc;this.cssSrc=a.cssSrc;this.scriptSrc=a.scriptSrc};
Zef.Visual.prototype.getComponentId=function(){return"undefined"!==typeof this.component&&null!==this.component.properties?"undefined"!==typeof this.component.parentComponent?!0===this.addParentIdToComponentId?this.component.parentComponent.name+"_"+this.component.name+"_"+this.component.parentComponent.id+"_"+this.component.properties.id:this.component.parentComponent.name+"_"+this.component.name+"_"+this.component.properties.id:this.component.name+"_"+this.component.properties.id:"undefined"};
Zef.Visual.prototype.addUiElement=function(){if("undefined"!==typeof this.htmlSrc)return this.constructElementFromTemplate();"undefined"!==typeof this.cssSrc&&Zef.loadCss(this,null,function(){});return this.constructDefaultElement()};Zef.Visual.prototype.removeUiElement=function(){"undefined"!==typeof this.element&&null!=this.element&&zefJQuery(this.element).remove()};
Zef.Visual.prototype.getContainerElement=function(){var a=this.containerClassName;!1===this.useContainerClassName&&"undefined"!==typeof this.component.indexInParent&&(a="zef_item_"+this.component.indexInParent);return this.component.parentComponent.visual.getContainer(a)};
Zef.Visual.prototype.getContainer=function(a){var b=zefJQuery(this.element);a=zefJQuery(b).find("."+a);if(a.length)return a[0];a=zefJQuery(b).find(".container");if(a.length)return a[0];a=zefJQuery(b).find("div");return a.length?a[0]:b};
Zef.Visual.prototype.constructDefaultElement=function(){var a="'",b=!1,c;for(c in this.settings)"function"!=typeof this.settings[c]&&("position"==c&&(b=!0),a="width"==c&&("number"==typeof this.settings[c]||0>this.settings[c].indexOf("px")&&0>this.settings[c].indexOf("PX")&&0>this.settings[c].indexOf("%"))?a+c+": "+this.settings[c]+"px; ":"height"==c&&("number"==typeof this.settings[c]||0>this.settings[c].indexOf("px")&&0>this.settings[c].indexOf("PX")&&0>this.settings[c].indexOf("%"))?a+c+": "+this.settings[c]+
"px; ":a+c+": "+this.settings[c]+"; ");!1==b&&(a+="position: relative; ");this.element=zefJQuery("<div style="+(a+"'")+'><input type="hidden" class="_compOrder_" id="_'+this.getComponentId()+'_idx" value="'+this.order+'"/></input></div>').appendTo(this.getContainerElement());this.component.uiDone=!0;!0==this.questionAnswered&&this.element&&(zefJQuery(this.element).addClass("question-answered"),zefJQuery(this.element).find("#"+this.getComponentId()).addClass("question-answered"));this.registerEvents();
this.visualDone();this._waitedCallDone=!0;this.component.uiDone=!0};Zef.Visual.prototype.getHTMLTemplate=function(){return Zef.loadedHtmlComponents[this.htmlSrc].html};Zef.Visual.prototype.replaceExtraFields=function(a){return a};Zef.Visual.prototype.getSettings=function(){return this.settings};Zef.Visual.prototype.getUiValue=function(){return this.component.uiValue};
Zef.Visual.prototype.replaceFields=function(a){a=a.replace(/{componentId}/g,this.getComponentId());"undefined"!==typeof this.getUiValue()&&(a=a.replace(RegExp("{defaultValue}","g"),this.getUiValue()));for(var b in this.component.properties)if("function"!=typeof this.component.properties[b]){var c=RegExp("{"+b+"}","g");a=a.replace(c,this.component.properties[b])}for(var d in this.getSettings())"function"!=typeof this.settings[d]&&(c=RegExp("{"+d+"}","g"),a=a.replace(c,this.settings[d]));"undefined"!==
typeof Zef._host&&0<=Zef._host.indexOf("zefengine.appspot")?(c=RegExp("{fbShareHost}","g"),a=a.replace(c,"zefengine.appspot.com")):(c=RegExp("{fbShareHost}","g"),a=a.replace(c,"www.votingaid.com"));this.component.player&&this.component.player.properties.cFKey&&(c=RegExp("{companyFriendlyKey}","g"),a=a.replace(c,this.component.player.properties.cFKey));this.component.player&&this.component.player.properties.fKey&&(c=RegExp("{appFriendlyKey}","g"),a=a.replace(c,this.component.player.properties.fKey));
if("undefined"!==typeof this.settings&&null!=this.settings&&"undefined"!==typeof this.settings.subComponentStyleNames)for(b=0;b<this.settings.subComponentStyleNames.length;b++){d=this.settings.subComponentStyleNames[b];var f=this.settings.subComponentStyles[b];"-"==f&&(f="");c=RegExp("{"+d+"/(.*?)}","g");a=a.replace(c,f);c=RegExp("{"+d+"}","g");a=a.replace(c,f)}if("undefined"!==typeof this.component.parentComponent.visual&&(b=this.component.parentComponent.visual.settings,"undefined"!==typeof b&&
null!=b&&"undefined"!==typeof b.subComponentStyleNames))for(d=0;d<b.subComponentStyleNames.length;d++){var f=b.subComponentStyleNames[d],e=b.subComponentStyles[d];"-"==e&&(e="");c=RegExp("{"+f+"/(.*?)}","g");a=a.replace(c,e);c=RegExp("{"+f+"}","g");a=a.replace(c,e)}return a};
Zef.Visual.prototype.constructElementFromTemplate=function(){var a=this;if("undefined"===typeof Zef.loadedHtmlComponentStatuses[this.htmlSrc]){Zef.loadedHtmlComponentStatuses[this.htmlSrc]="loading";Zef.loadedHtmlComponents[this.htmlSrc]={};if("undefined"===typeof this._waitedCallDone||!0==this._waitedCallDone)Zef.log("loading ui for "+this.getComponentId()+" (order: "+this.order+")"),Zef._ZefUiComponentCallQueue.push([this,"constructElementFromTemplate"]),this._waitedCallDone=!1;Zef.loadHtml(this,
Zef.loadedHtmlComponents[this.htmlSrc],function(){Zef.loadedHtmlComponentStatuses[a.htmlSrc]="loaded";setTimeout("Zef.executeUiComponentCallQueue()",5)})}else if("loading"==Zef.loadedHtmlComponentStatuses[this.htmlSrc])Zef.log("waiting for ui to load for "+this.getComponentId()+" (order: "+this.order+")"),Zef._ZefUiComponentCallQueue.push([this,"constructElementFromTemplate"]),this._waitedCallDone=!1;else if(Zef.loadedHtmlComponents[this.htmlSrc].html)if(!0===this.component.uiDone)Zef.log("ui already done for component "+
this.getComponentId());else if(Zef.log("now constructing ui for "+this.getComponentId()+" (order: "+this.order+")"),!1===this.component.parentComponent.uiDone)Zef.log("parent for component "+this.getComponentId()+" not yet ready, waiting"),Zef._ZefUiComponentCallQueue.push([this,"constructElementFromTemplate"]);else{var b=this.getHTMLTemplate(),b=this.replaceFields(b),b=this.replaceExtraFields(b),c="";if(!1===this.skipStyle){var c="'",d=!1;for(sett in this.settings)"subComponentStyleNames"!==sett&&
"subComponentStyles"!==sett&&("position"==sett&&(d=!0),"-"!=this.settings[sett]&&(c="width"==sett&&("number"==typeof this.settings[sett]||0>this.settings[sett].indexOf("px")&&0>this.settings[sett].indexOf("PX")&&0>this.settings[sett].indexOf("%"))?c+sett+": "+this.settings[sett]+"px; ":"height"==sett&&("number"==typeof this.settings[sett]||0>this.settings[sett].indexOf("px")&&0>this.settings[sett].indexOf("PX")&&0>this.settings[sett].indexOf("%"))?c+sett+": "+this.settings[sett]+"px; ":c+sett+": "+
this.settings[sett]+"; "));for(var f=0;0<=f;)if(f=b.indexOf('style="{',f),0>f&&(f=b.indexOf("style='{",f)),0<=f){var f=f+8,e=b.indexOf("/",f),g=b.indexOf("}",f);if(0>e||e>g)e=g;if(e<g)var h=b.substr(f,e-f),e=b.substr(e+1,g-e-1),b=b.replace(RegExp("{"+h+"/(.*?)}","g"),e)}!1===d&&(c+="position: relative; ");c+="'"}var d=this.getContainerElement(),j=null;!0===this.clearContainer?zefJQuery(d).empty():!1===this.skipOrder&&("undefined"!==typeof this.order?zefJQuery(d).children().each(function(){var b=zefJQuery(this).data("order");
"undefined"!==typeof b&&b<a.order&&(null===j?j=this:null!=j&&b>zefJQuery(j).data("order")&&(j=this))}):Zef.log(this.getComponentId()+" order is undefined"));null===j?(c=zefJQuery("<div class='"+this.component.name+"_added' style="+c+'><input type="hidden" class="_compOrder_" id="_'+this.getComponentId()+'_idx" value="'+this.order+'"/></input></div>').prependTo(d),zefJQuery(b).appendTo(c),this.element=c):(c=zefJQuery("<div style="+c+'><input type="hidden" class="_compOrder_" id="_'+this.getComponentId()+
'_idx" value="'+this.order+'"/></input></div>').insertAfter(j),zefJQuery(b).appendTo(c),this.element=c,wasAdded=!0);b=0;"undefined"!==typeof this.order&&(b=this.order);zefJQuery(this.element).data("order",b);!0==this.questionAnswered&&this.element&&(zefJQuery(this.element).addClass("question-answered"),zefJQuery(this.element).find("#"+this.getComponentId()).addClass("question-answered"));this.registerEvents();this.visualDone();this._waitedCallDone=!0;this.component.uiDone=!0}};
Zef.Visual.prototype.setAnswered=function(a){this.questionAnswered=a;!0==this.questionAnswered?(this.element&&zefJQuery(this.element).addClass("question-answered"),zefJQuery("#"+this.getComponentId()).addClass("question-answered")):(this.element&&zefJQuery(this.element).removeClass("question-answered"),zefJQuery("#"+this.getComponentId()).removeClass("question-answered"))};
Zef.Visual.prototype.setValueDisabled=function(a){this.element&&(a?(zefJQuery(this.element).addClass("zg-input-disabled"),zefJQuery("#"+this.getComponentId()).addClass("zg-input-disabled")):(zefJQuery(this.element).removeClass("zg-input-disabled"),zefJQuery("#"+this.getComponentId()).removeClass("zg-input-disabled")))};
Zef.Visual.prototype.visualDone=function(){"undefined"!==typeof this.component.restoredValue&&null!=this.component.restoredValue&&(this.setInputValue(this.component.restoredValue),this.component.restoredValue=null)};Zef.Visual.prototype.registerEvents=function(){this.component.inputValue=this.getInputValue();var a=this;zefJQuery("#"+this.getComponentId()).bind("change",function(b,c){a.fireValueChanged(c)});zefJQuery("#"+this.getComponentId()).bind("slidechange",function(b,c){a.fireValueChanged(c)})};
Zef.Visual.prototype.fireValueChanged=function(a){"undefined"!==typeof a&&null!=a?this.component.uiValue=a.value:(this.component.uiValue=null,this.component.uiValue=this.getInputValue());!1!==this.component.uiDone&&(this.component.questionAnswered=!0,Zef._questionAnsweredCache[this.component.id]=!0,this.element&&zefJQuery(this.element).addClass("question-answered"),zefJQuery("#"+this.getComponentId()).addClass("question-answered"),"undefined"!==typeof this.component.player&&this.component.player.handleInputValueChanged(this.component.properties.id,
this.component.uiValue,this.component))};Zef.Visual.prototype.fireItemSelected=function(a,b){!1!==this.component.uiDone&&"undefined"!==typeof this.component.player&&this.component.player.handleItemSelected(this.component.properties.id,this.component,b)};Zef.Visual.prototype.getInputValue=function(){return"undefined"!==typeof this.component.uiValue&&null!==this.component.uiValue?this.component.uiValue:zefJQuery("#"+this.getComponentId()).value};
Zef.Visual.prototype.setInputValue=function(a){this.component.uiValue=a;zefJQuery("#"+this.getComponentId()).val(a)};Zef.Visual.prototype.isDisableInCalculation=function(){return!1};Zef.Visual.prototype.toggleCalculationActivity=function(){};Zef.Visual.prototype.inputValueChanged=function(){};Zef.QuestionList=function(){this.name="questions"};Zef.QuestionList.prototype=new Zef.Component;Zef.AjaxQuestionList=function(){this.name="questions";this.selectedComponent=null};
Zef.AjaxQuestionList.prototype=new Zef.Component;Zef.AjaxQuestionList.prototype.getChildComponents=function(){null==this.selectedComponent&&0<this.components.size&&(this.selectedComponent=this.components.value());var a=new Map;"undefined"!==typeof this.selectedComponent&&null!=this.selectedComponent&&a.put(this.selectedComponent.name,this.selectedComponent);return a};Zef.AjaxQuestionList.prototype.nextQuestion=function(){this.components.next();this.selectedComponent=this.components.value()};
Zef.AjaxQuestionList.prototype.inputValueChanged=function(){this.nextQuestion()};Zef.Group=function(){this.name="group"};Zef.Group.prototype=new Zef.Component;Zef.Group.prototype.needsRebuildOnInputChange=function(){return!1};Zef.Group.prototype.recalculate=function(){this.visual&&this.visual.recalculateAnswered()};Zef.GroupQuestionList=function(){this.name="groupQuestions"};Zef.GroupQuestionList.prototype=new Zef.QuestionList;Zef.ComparingQuestionList=function(){this.name="comparingQuestions"};
Zef.ComparingQuestionList.prototype=new Zef.QuestionList;
Zef.Player=function(){this.name="player";this.player=this;this.parentComponent=new Zef.Component;this.parentComponent.visual=new Zef.PlayerVisual;this.parentComponent.uiDone=!0;this.answerer=null;this.anonymous=!1;Zef._questionAnsweredCache={};if("undefined"!==typeof FB){var a=this;FB.getLoginStatus(function(){FB.api("/me",function(b){"undefined"!=typeof b.name?(a.fbUserName=""+b.name,a.fbFirstName=""+b.first_name,a.fbLastName=""+b.last_name):setTimeout(function(){FB.api("/me",function(b){"undefined"!=
typeof b.name&&(a.fbUserName=""+b.name,a.fbFirstName=""+b.first_name,a.fbLastName=""+b.last_name)})},1E4)})})}};Zef.Player.prototype=new Zef.Component;Zef.Player.prototype.constructUi=function(a,b,c){a=zefJQuery(a);if(b)var d=zefJQuery(b);if(c)var f=zefJQuery(c);this.playerElement=this.parentComponent.visual.element=a;this.questionListElement=d;this.resultListElement=f;this.buildUi();this.playerElement&&this.playerElement.addClass("player-"+Zef._playerId)};
Zef.Player.prototype.loadDone=function(){"function"==typeof this.loadDoneCallback&&(this.loadDoneCallback(),delete this.loadDoneCallback)};Zef.Player.prototype.loadI18n=function(a,b){a.properties&&a.properties.locales?Zef.loadScriptDebug(a.properties.locales,function(){this.i18nLoaded=!0;b()}):(this.i18nLoaded=!0,b())};Zef.Player.prototype.reapplyI18n=function(){this.processChildComponentsUntil(this.getChildComponents(),function(a){null!==a.properties&&a.applyI18n()},function(){return!1})};
Zef.Player.prototype.handleComponents=function(a){if("undefined"==typeof this.i18nLoaded){var b=this;this.loadI18n(a,function(){Zef.Component.prototype.handleComponents.call(b,a)})}else Zef.Component.prototype.handleComponents.call(this,a)};Zef.Player.prototype.load=function(){"undefined"!==typeof Zef._globalPlayerData?(this.handleComponents(Zef._globalPlayerData),this.loadDone()):Zef.Component.prototype.load.call(this)};Zef.Player.prototype.setAnswererKey=function(a){this.answerer=a};
Zef.Player.prototype.setAnonymous=function(a){this.anonymous=a};Zef.Player.prototype.inputValueChanged=function(){};Zef.Player.prototype.getValueForInput=function(a){var b=-1;this.processChildComponentsUntil(this.getChildComponents(),function(c){null!==c.properties&&(c.properties.id==a&&"undefined"!==typeof c.visual&&null!=c.visual)&&(b=c.visual.getInputValue())},function(){return 0<=b});return b};
Zef.Player.prototype.isDisableInCalculation=function(a){if("undefined"!==typeof Zef["_cachedQuestionDisabled_"+a])return Zef["_cachedQuestionDisabled_"+a];var b=null;this.processChildComponentsUntil(this.getChildComponents(),function(c){null!==c.properties&&("question"==c.category&&"undefined"!==typeof c.visual&&null!=c.visual)&&(Zef["_cachedQuestionDisabled_"+a]=c.visual.isDisableInCalculation(),c.properties.id==a&&(b=c.visual.isDisableInCalculation()))},function(){return!1});return Zef["_cachedQuestionDisabled_"+
a]=b};Zef.Player.prototype.answeredQuestionCount=function(){if(Object.keys)return Object.keys(Zef._questionAnsweredCache).length;var a=0;for(k in Zef._questionAnsweredCache)Object.prototype.hasOwnProperty.call(Zef._questionAnsweredCache,k)&&++a;return a};Zef.Player.prototype.answeredQuestionCountToRequired=function(){var a=0,b=this.getRequiredQuestions(),c;for(c in b)"function"!=typeof b[c]&&this.questionAnswered(b[c].id)&&(a+=1);return a};
Zef.Player.prototype.questionAnswered=function(a){return"undefined"!==typeof Zef._questionAnsweredCache[a]?Zef._questionAnsweredCache[a]:!1};Zef.Player.prototype.processChildComponentsUntil=function(a,b,c){var d=this;a.each(function(a,e){b(e);c()||"undefined"!==typeof e.getChildComponents()&&0<e.getChildComponents().size&&d.processChildComponentsUntil(e.getChildComponents(),b,c)})};
Zef.Player.prototype.getQuestions=function(){if("undefined"!==typeof Zef._cachedQuestions)return Zef._cachedQuestions;var a=[];this.processChildComponentsUntil(this.getChildComponents(),function(b){"undefined"!==typeof b.category&&"question"===b.category&&a.push(b)},function(){return!1});return Zef._cachedQuestions=a};
Zef.Player.prototype.getQuestion=function(a){var b=null;if("undefined"!==typeof Zef["_cachedQuestion_"+a])return Zef["_cachedQuestion_"+a];this.processChildComponentsUntil(this.getChildComponents(),function(c){"undefined"!==typeof c.category&&"question"===c.category&&(c.properties.id==a&&(b=c),Zef["_cachedQuestion_"+c.properties.id]=c)},function(){return!1});return Zef["_cachedQuestion_"+a]=b};
Zef.Player.prototype.getFilteringQuestions=function(){if("undefined"!==typeof Zef._cachedFilteredQuestions)return Zef._cachedFilteredQuestions;var a=[];this.processChildComponentsUntil(this.getChildComponents(),function(b){"undefined"!==typeof b.category&&"question"===b.category&&!0===b.properties.filter&&a.push(b)},function(){return!1});return Zef._cachedFilteredQuestions=a};
Zef.Player.prototype.getRequiredQuestions=function(){if("undefined"!==typeof Zef._cachedRequiredQuestions)return Zef._cachedRequiredQuestions;var a=[];this.processChildComponentsUntil(this.getChildComponents(),function(b){"undefined"!==typeof b.category&&"question"===b.category&&!0===b.properties.required&&a.push(b)},function(){return!1});return Zef._cachedRequiredQuestions=a};
Zef.Player.prototype.getResult=function(a){if(this.components.get("ResultList")){var b=this.components.get("ResultList");if(b.properties&&b.properties.replies)for(var c in b.properties.replies)if("function"!=typeof b.properties.replies[c]&&b.properties.replies[c].answererId==a)return b.properties.replies[c]}};Zef.Player.prototype.setBestResult=function(a){var b=this.getResult(a);b&&(this.bestresult=new Zef.TargetResult,this.bestresult.id=a,this.bestresult.properties=b)};
Zef.Player.prototype.getBestResult=function(){var a=null;if(this.components.get("ResultList")){var b=this.components.get("ResultList");if(b.components){var b=b.components.listValues(),c;for(c in b)"function"!=typeof b[c]&&(null==a?a=b[c]:a.rawPercentage<b[c].rawPercentage&&(a=b[c]))}}null==a&&this.bestresult&&(a=this.bestresult);return a};
Zef.Player.prototype.getComponent=function(a){if(this.components.get(a))return this.components.get(a);var b=this.components.listValues(),c;for(c in b)if("function"!=typeof b[c]&&b[c].componentName==a)return b[c];return null};Zef.Player.prototype.showComponent=function(a){if(this.components.get(a))this.components.get(a).show();else{var b=this.components.listValues(),c;for(c in b)if("function"!=typeof b[c]&&b[c].componentName==a){b[c].show();break}}};
Zef.Player.prototype.getQuestionCount=function(){if("undefined"!==typeof Zef._cachedQuestionCount)return Zef._cachedQuestionCount;var a=0;this.processChildComponentsUntil(this.getChildComponents(),function(b){"undefined"!==typeof b.category&&"question"===b.category&&(a+=1)},function(){return!1});return Zef._cachedQuestionCount=a};Zef.Question1d=function(){this.name="line1d";this.category="question"};Zef.Question1d.prototype=new Zef.Component;
Zef.Question1d.prototype.rebuildUi=function(){"undefined"!==typeof this.parentComponent&&null!=this.parentComponent?this.parentComponent.rebuildUi():Zef.Component.prototype.rebuildUi.call(this)};Zef.Question1d.prototype.needsRebuildOnInputChange=function(){return!1};Zef.QuestionText=function(){this.name="text";this.category="question"};Zef.QuestionText.prototype=new Zef.Component;Zef.QuestionText.prototype.needsRebuildOnInputChange=function(){return!1};
Zef.AnsweredQuestion1d=function(){this.name="answer1d";this.category="answer"};Zef.AnsweredQuestion1d.prototype=new Zef.Component;Zef.AnsweredQuestion1d.prototype.rebuildUi=function(){"undefined"!==typeof this.parentComponent&&null!=this.parentComponent?this.parentComponent.rebuildUi():Zef.Component.prototype.rebuildUi.call(this)};Zef.AnsweredQuestion1d.prototype.needsRebuildOnInputChange=function(){return!1};Zef.AnsweredText=function(){this.name="answertext";this.category="answer"};
Zef.AnsweredText.prototype=new Zef.Component;Zef.AnsweredText.prototype.rebuildUi=function(){"undefined"!==typeof this.parentComponent&&null!=this.parentComponent?this.parentComponent.rebuildUi():Zef.Component.prototype.rebuildUi.call(this)};Zef.AnsweredText.prototype.needsRebuildOnInputChange=function(){return!1};Zef.QuestionChoice=function(){this.name="choice";this.category="question"};Zef.QuestionChoice.prototype=new Zef.Component;
Zef.ReplySaver=function(){this.name="replySaver";this.savePerforming=this.loadContent=this.hasVisual=!1;this.saveQueue=[]};Zef.ReplySaver.prototype=new Zef.Component;Zef.ReplySaver.prototype.setSavedCallback=function(a){this.savedCallback=a};
Zef.ReplySaver.prototype.inputValueChanged=function(a,b,c){var d="unknown",f="";if(null!=this.player){if("undefined"!==typeof this.player.tags)var e=this.player.tags;d=this.player.answerer;f=this.player.anonymous}"undefined"===typeof e&&(e=[]);var g="undefined";"undefined"!=typeof c&&null!=c&&(g=c.name);var h="0";"undefined"!=typeof c&&(null!=c&&"undefined"!=typeof c.properties&&null!=c.properties&&"undefined"!==typeof c.properties.qv)&&(h=c.properties.qv);c=""+g;for(var j in e)"function"!=typeof e[j]&&
(c+=",",c+=e[j]);this.saveToServer(a,b,g,c,d,f,h)};
Zef.ReplySaver.prototype.saveToServer=function(a,b,c,d,f,e,g){if(!0===this.savePerforming)this.saveQueue.push([a,b,c,d,f,e,g]);else{this.savePerforming=!0;var h=this;Zef.loadFromServer("saveReply",{id:a,value:b,type:c,tags:d,answerer:f,anon:e,ver:g},function(b){if("undefined"!==typeof b&&(null!=b&&"undefined"!==typeof b.answererKey)&&(h.player.setAnswererKey(b.answererKey),h.player.setAnonymous(!0),h.saveQueue.length))for(var c in h.saveQueue)"function"!=typeof h.saveQueue[c]&&(h.saveQueue[c][5]=
!0);"function"===typeof this.savedCallback&&h.savedCallback(a,newValue,component)},function(){},function(){h.checkSaveQueue()})}};
Zef.ReplySaver.prototype.checkSaveQueue=function(){var a=this;if(this.saveQueue.length)for(var b=this.saveQueue.shift();b;){if(("undefined"===typeof b[4]||null==b[4])&&"undefined"!==typeof a.player.answerer&&null!==a.player.answerer)b[4]=a.player.answerer;Zef.loadFromServer("saveReply",{id:b[0],value:b[1],type:b[2],tags:b[3],answerer:b[4],anon:b[5],ver:b[6]},function(b){"undefined"!==typeof b&&(null!=b&&"undefined"!==typeof b.answererKey)&&(a.player.setAnswererKey(b.answererKey),a.player.setAnonymous(!0));
"function"===typeof this.savedCallback&&a.savedCallback(componentId,newValue,component)},function(){},function(){});b=this.saveQueue.shift()}this.savePerforming=!1};Zef.Result=function(){this.name="result"};Zef.Result.prototype=new Zef.Component;
Zef.Result.prototype.itemSelected=function(a,b,c){"undefined"!==typeof this.visual&&(a===this.id?!0===c?"undefined"!==typeof this.visual.drawSelected&&this.visual.drawSelected():"undefined"!==typeof this.visual.drawUnselected&&this.visual.drawUnselected():"undefined"!==typeof this.visual.drawUnselected&&this.visual.drawUnselected())};Zef.TargetResult=function(){this.name="targetResult"};Zef.TargetResult.prototype=new Zef.Result;
Zef.TargetResult.prototype.buildVisual=function(a){"undefined"===typeof this.player.cachedTargetVisual&&(this.player.cachedTargetVisual=a);Zef.Component.prototype.buildVisual.call(this,a)};Zef.FolderResult=function(){this.name="folderResult"};Zef.FolderResult.prototype=new Zef.Result;Zef.FolderResult.prototype.buildVisual=function(a){"undefined"===typeof this.player.cachedFolderVisual&&(this.player.cachedFolderVisual=a);Zef.Component.prototype.buildVisual.call(this,a)};
Zef.ResultList=function(){this.name="results"};Zef.ResultList.prototype=new Zef.Component;Zef.ResultList.prototype.recalculate=function(){this.visual?this.visual.redrawResults():this.hasEnoughAnswers()&&this.rebuildUi()};Zef.ResultList.prototype.hasEnoughAnswers=function(){if("undefined"==typeof this.properties.threshold)return!0;var a=!1;return a=this.properties.onlyRequired?this.player.answeredQuestionCountToRequired()>=this.properties.threshold:this.player.answeredQuestionCount()>=this.properties.threshold};
Zef.ResultList.prototype.inputValueChanged=function(){this.hasEnoughAnswers()&&("undefined"==typeof this.visual||null==this.visual)&&this.buildVisual(this.loadedUiData)};Zef.ResultList.prototype.buildVisual=function(a){this.loadedUiData=a;!1!==this.hasEnoughAnswers()&&Zef.Component.prototype.buildVisual.call(this,a)};
Zef.ResultList.prototype.loadRepliesAndRedraw=function(a){var b=this;this.visual.showLoading();zefJQuery.ajax({url:Zef._repliesUrl+a,success:function(c){b.properties.replies=c.replies;b.visual.loadedRepliesKey=a;b.visual.loadedResults=[];b.visual.redrawResults(1);b.visual.hideLoading()},error:function(){b.visual.hideLoading()},dataType:"jsonp",complete:function(){b.visual.hideLoading()},jsonpCallback:"jsonpCb"})};
Zef.ResultList.prototype.loadResultsAndCalculate=function(a){var b=this;this.visual.showLoading();zefJQuery.ajax({url:Zef._calculationUrl+a,success:function(c){b.visual.loadedResults[a]=c.replies;b.visual.usePrecalculatedAndDraw();b.visual.hideLoading()},error:function(){b.visual.hideLoading()},dataType:"jsonp",complete:function(){b.visual.hideLoading()},jsonpCallback:"jsonpCb"})};Zef.OwnReplies=function(){this.name="ownReplies"};Zef.OwnReplies.prototype=new Zef.Component;
Zef.OwnReplies.prototype.handleInputValueChanged=function(a,b,c){this.inputValueChanged(a,b,c);"undefined"!==typeof this.visual&&null!=this.visual&&this.visual.inputValueChanged(a,b,c);this.components.each(function(d,f){f.handleInputValueChanged(a,b,c)});c==this&&this.rebuildUi()};Zef.ResultListSaver=function(){this.name="resultListSaver";var a=this;this.loadContent=this.hasVisual=!1;zefJQuery(window).unload(function(){a.storeResultList()})};Zef.ResultListSaver.prototype=new Zef.Component;
Zef.ResultListSaver.prototype.setSavedCallback=function(a){this.savedCallback=a};
Zef.ResultListSaver.prototype.storeResultList=function(){if(null!=this.player){var a=null;this.player.processChildComponentsUntil(this.player.getChildComponents(),function(b){"results"==b.name&&(a=b)},function(){return null!=a});if(null!=a){var b=[],c=0;"undefined"!=typeof a.components&&null!=a.components&&a.components.each(function(a,f){"targetResult"==f.name&&(b[c++]={targetId:f.properties.id,percentage:f.properties.hitPercentage})});Zef.loadFromServerSync("saveHits",{answerer:this.player.answerer,
anon:this.player.anonymous,hits:b},function(){},function(){},function(){})}}};Zef.SelectedResults=function(){this.name="selectedResults"};Zef.SelectedResults.prototype=new Zef.Component;Zef.SelectedResults.prototype.itemSelected=function(a,b,c){this.selectedProperties=this.properties.asPopup?b.properties:c?b.properties:null;this.properties.showComparison&&this.addComparison();this.rebuildUi();setTimeout("Zef.executeUiComponentCallQueue()",5)};
Zef.SelectedResults.prototype.addComparison=function(){var a=new Zef.Component;a.name="comparison";a.id=this.id;a.properties={};a.properties.id=this.id;a.parentComponent=this;a.uiData={};a.uiData.visual="Zef.ReplyComparisonQuestionListVisual";a.uiData.htmlSrc="/components/html/questionlistComparison.html";a.uiData.cssSrc=this.properties.comparisonListCss;a.componentLoadDone=!0;a.player=this.player;a.uiLoaded=!0;this.components.put("comp",a);a.buildUi();var b=this;this.player.components.get("questions").components.each(function(c,
d){if("group"==d.name){var f=new Zef.Component;f.name="comparisonGroup";f.uiData=d.uiData;f.uiData.visual="Zef.GroupVisual";f.uiData.cssSrc=b.properties.comparisonGroupCss;f.uiData.htmlSrc="/components/html/rtce/comparisonGroup.html";f.properties=d.properties;f.id=d.id;a.components.put(d.name+f.id,f);f.parentComponent=a;f.componentLoadDone=!0;f.uiLoaded=!0;f.player=this.player;f.indexInParent=d.indexInParent;f.buildUi();d.components.each(function(a,c){if("line1d"==c.name){if(c.parentComponent.id==
f.id){var d=new Zef.AnsweredQuestion1d;d.uiData=c.uiData;d.uiData.visual="Zef.Answer1dVisual";d.uiData.cssSrc=b.properties.comparison1dCss;d.uiData.htmlSrc="/components/html/rtce/answer1d.html";d.properties={};for(var e in c.properties)"function"!=typeof c.properties[e]&&(d.properties[e]=c.properties[e]);d.id=c.id;d.properties.ownValue=!0===c.player.questionAnswered(d.id)?c.player.getValueForInput(d.id):"na";for(e in b.selectedProperties.replies)if("function"!=typeof b.selectedProperties.replies[e]){var g=
b.selectedProperties.replies[e];g.q==d.id&&(d.properties.targetValue=g.v,"undefined"===typeof d.properties.targetValue&&(d.properties.targetValue="na"))}"undefined"==typeof d.properties.targetValue&&(d.properties.targetValue="na");"undefined"==typeof d.properties.ownValue&&(d.properties.ownValue="na");f.components.put(c.name+c.id,d);d.parentComponent=f;d.componentLoadDone=!0;d.uiLoaded=!0;d.player=this.player;d.indexInParent=c.indexInParent;d.buildUi()}}else if("text"==c.name&&c.parentComponent.id==
f.id){d=new Zef.AnsweredText;d.uiData=c.uiData;d.uiData.visual="Zef.AnswerTextVisual";d.uiData.cssSrc=b.properties.comparisonTextCss;d.uiData.htmlSrc="/components/html/rtce/answertext.html";d.properties={};for(e in c.properties)"function"!=typeof c.properties[e]&&(d.properties[e]=c.properties[e]);d.id=c.id;for(e in b.selectedProperties.replies)"function"!=typeof b.selectedProperties.replies[e]&&(g=b.selectedProperties.replies[e],g.q==d.id&&(d.properties.targetValue=g.va,"undefined"===typeof d.properties.targetValue&&
(d.properties.targetValue=null),null==d.properties.targetValue&&(d.properties.targetValue="")));"undefined"===typeof d.properties.targetValue&&(d.properties.targetValue=null);null==d.properties.targetValue&&(d.properties.targetValue="");f.components.put(c.name+c.id,d);d.parentComponent=f;d.componentLoadDone=!0;d.uiLoaded=!0;d.player=this.player;d.indexInParent=c.indexInParent;d.buildUi()}})}else if("line1d"==d.name){var e=new Zef.AnsweredQuestion1d;e.uiData=d.uiData;e.uiData.visual="Zef.Answer1dVisual";
e.uiData.cssSrc=b.properties.comparison1dCss;e.uiData.htmlSrc="/components/html/rtce/answer1d.html";e.id=d.id;e.properties=d.properties;e.properties.ownValue=!0===d.player.questionAnswered(e.id)?d.player.getValueForInput(e.id):null;for(var g in b.selectedProperties.replies)"function"!=typeof b.selectedProperties.replies[g]&&b.selectedProperties.replies[g].q==e.id&&(e.properties.targetValue=e.v,"undefined"===typeof e.properties.targetValue&&(e.properties.targetValue=null));"undefined"===typeof e.properties.targetValue&&
(e.properties.targetValue=null);a.components.put(d.name+e.id,e);e.parentComponent=a;e.componentLoadDone=!0;e.uiLoaded=!0;e.player=this.player;e.indexInParent=d.indexInParent;e.buildUi()}})};Zef.FacebookShare=function(){this.name="fbshare"};Zef.FacebookShare.prototype=new Zef.Component;Zef.FacebookCommenting=function(){this.name="fbcomments"};Zef.FacebookCommenting.prototype=new Zef.Component;Zef.InfoPopup=function(){this.name="InfoPopup"};Zef.InfoPopup.prototype=new Zef.Component;
Zef.InfoPopup.prototype.needsRebuildOnInputChange=function(){return!1};Zef.Link=function(){this.name="Link"};Zef.Link.prototype=new Zef.Component;Zef.Link.prototype.needsRebuildOnInputChange=function(){return!1};Zef.InfoPopup=function(){this.name="InfoPopup"};Zef.InfoPopup.prototype=new Zef.Component;Zef.InfoPopup.prototype.needsRebuildOnInputChange=function(){return!1};Zef.TwitterShare=function(){this.name="twittershare"};Zef.TwitterShare.prototype=new Zef.Component;
Zef.AnswerLoader=function(){this.name="answerLoader";this.hasVisual=this.loadContent=!1};Zef.AnswerLoader.prototype=new Zef.Component;
Zef.AnswerLoader.prototype.init=function(){if(this.player&&this.player.components){var a=this.player.components.get("selectedResults");if("undefined"!==typeof a)for(var b in a.properties.replies)if("function"!=typeof a.properties.replies[b]){var c=a.properties.replies[b],d=this.player.getQuestion(c.q);if("undefined"!==typeof d&&null!=d&&("undefined"!==typeof c.v||"undefined"!==typeof c.va))d.questionAnswered=!0,"undefined"!==typeof d.visual&&null!=d.visual&&d.visual.setAnswered(!0),"line1d"==d.name?
("undefined"!==typeof d.visual&&null!=d.visual&&d.visual.setInputValue(c.v),d.restoredValue=c.v):"choice"==d.name?(d.restoredValue=c.v,"undefined"!==typeof d.visual&&null!=d.visual&&d.visual.setInputValue(c.v)):"text"==d.name&&(d.restoredValue=c.va,"undefined"!==typeof d.visual&&null!=d.visual&&d.visual.setInputValue(c.va))}}};Zef.QuestionSound=function(){this.name="QuestionSound"};Zef.QuestionSound.prototype=new Zef.Component;Zef.QuestionSound.prototype.needsRebuildOnInputChange=function(){return!1};
Zef.PreviewReplyRecorder=function(){this.name="previewReplyRecorder";this.loadContent=this.hasVisual=!1;if("undefined"!==typeof Zef._keptReplies||null==Zef._keptReplies)Zef._keptReplies={}};Zef.PreviewReplyRecorder.prototype=new Zef.Component;Zef.PreviewReplyRecorder.prototype.setSavedCallback=function(a){this.savedCallback=a};Zef.PreviewReplyRecorder.prototype.inputValueChanged=function(a,b){Zef._keptReplies[a]=b};
Zef.PreviewReplyRecorder.prototype.restoreReplies=function(){for(var a in Zef._keptReplies)"function"!=typeof Zef._keptReplies[a]&&this.player.handleInputValueChanged(a,Zef._keptReplies[a],null)};Zef.ResultProgress=function(){this.name="ResultProgress"};Zef.ResultProgress.prototype=new Zef.Component;Zef.DynamicContent=function(){this.name="DynamicContent"};Zef.DynamicContent.prototype=new Zef.Component;
Zef.DynamicContent.prototype.inputValueChanged=function(a){if("undefined"!==typeof this.properties.questions&&this.listensToQuestion(a)){a=this.properties.content;var b=RegExp("{replyCount}","g");a=a.replace(b,this.player.answeredQuestionCount());for(var c=0;c<this.properties.questions.length;c++){var b=RegExp("{q"+this.properties.questions[c]+"}","g"),d=this.player.getQuestion(this.properties.questions[c]),f=this.player.getValueForInput(this.properties.questions[c]);if("choice"==d.name&&f&&0<f.indexOf("_")){var e=
f=f.substring(f.lastIndexOf("_")+1),f=d.properties.choices[e];a=a.replace(RegExp("{i"+this.properties.questions[c]+"}","g"),e)}a=a.replace(b,f)}"undefined"!==typeof this.visual&&null!=this.visual&&this.visual.showContent(a)}};Zef.DynamicContent.prototype.listensToQuestion=function(a){for(var b=0;b<this.properties.questions.length;b++)if(this.properties.questions[b]===a)return!0;return!1};Zef.ScriptExecutor=function(){this.name="ScriptExecutor";this.run=this.loadContent=this.hasVisual=!1};
Zef.ScriptExecutor.prototype=new Zef.Component;Zef.ScriptExecutor.prototype.needsRebuildOnInputChange=function(){return!1};
Zef.ScriptExecutor.prototype.inputValueChanged=function(a){1===this.properties.when&&("undefined"!==typeof this.properties.answerCount&&0<this.properties.answerCount&&this.properties.answerCount<=this.player.answeredQuestionCount()&&this.runScript(),"undefined"!==typeof this.properties.questionId?this.properties.questionId===a&&this.runScript():"undefined"==typeof this.properties.questionId&&"undefined"==typeof this.properties.answerCount&&this.runScript())};
Zef.ScriptExecutor.prototype.runScript=function(){if(!1==this.run||!1==this.properties.runOnce)zefJQuery.globalEval(this.properties.code),this.run=!0};Zef.ScriptExecutor.prototype.componentsLoaded=function(){0===this.properties.when&&this.runScript()};Zef.TargetComparing=function(){this.name="TargetComparing"};Zef.TargetComparing.prototype=new Zef.Component;Zef.TargetComparing.prototype.inputValueChanged=function(){};
Zef.TargetComparing.prototype.registerEvents=function(){var a=this;zefJQuery(".zg_targetComparing").addClass("player-"+this.component.player.id);zefJQuery(".zg_targetComparing").bind("click",function(){a.showPopup();return!1})};Zef.TargetComparing.prototype.showPopup=function(){zefJQuery(".zg_targetComparingPopup").dialog("open")};Zef.ResultFBShare=function(){this.name="ResultFBShare"};Zef.ResultFBShare.prototype=new Zef.Component;Zef.ResultTwitterShare=function(){this.name="ResultTwitterShare"};
Zef.ResultTwitterShare.prototype=new Zef.Component;Zef.StartInfo=function(){this.name="StartInfo"};Zef.StartInfo.prototype=new Zef.Component;Zef.StartInfo.prototype.needsRebuildOnInputChange=function(){return!1};
Zef.StartInfo.prototype.buildVisual=function(a){zefJQuery(".zef_item_1").hide();zefJQuery(".zef_item_2").hide();zefJQuery(".zef_item_3").hide();zefJQuery("body").append('<div class="zg_startInfoLoadIndicatorContainer player-'+this.player.id+'"><div class="zg_startInfoLoading"></div></div>');this.properties.canSkipPlayer?this.checkAnsweredAndContinue(a):this.showStartInfo(a);if(window.location&&window.location.search&&0<=window.location.search.indexOf("request_ids=")&&(a=window.location.search.indexOf("request_ids=")+
12,a=decodeURIComponent(window.location.search.substring(a,window.location.search.indexOf("&",a+1)))))if(a=a.split(","))for(var b in a)"function"!=typeof a[b]&&FB.api(a[b],"delete",function(){});FB.api("/me/apprequests",function(a){for(var b=0,f=a.data.length;b<f;b++)"function"!=typeof a.data[b]&&FB.api("/"+a.data[b].id,"DELETE",function(){})})};
Zef.StartInfo.prototype.checkAnsweredAndContinue=function(a){var b=this;Zef.queryDataServer("getResult",{},function(c){c&&c.r&&b.properties.playerSkipComponent?(b.player.setBestResult(c.r),b.player.showComponent(b.properties.playerSkipComponent),zefJQuery(".zg_startInfoLoadIndicatorContainer").remove()):b.showStartInfo(a)},function(){b.showStartInfo(a)},function(){})};
Zef.StartInfo.prototype.showStartInfo=function(a){var b=this;Zef._startInfoShown?(this.player.bestresult&&this.properties.playerSkipComponent&&this.player.showComponent(this.properties.playerSkipComponent),zefJQuery(".zef_item_1").show(),zefJQuery(".zef_item_2").show(),zefJQuery(".zef_item_3").show(),zefJQuery(".zg_startInfoLoadIndicatorContainer").remove()):"undefined"==typeof this.player.fbFriendGuesses||null==this.player.fbFriendGuesses?this.loadFbFriendGuesses(function(){b.checkResultAndDrawVisual(a);
zefJQuery(".zg_startInfoLoadIndicatorContainer").remove()}):(b.checkResultAndDrawVisual(a),zefJQuery(".zg_startInfoLoadIndicatorContainer").remove())};
Zef.StartInfo.prototype.checkResultAndDrawVisual=function(a){if(this.player.fbFriendGuesses){var b={},c=0,d;for(d in this.player.fbFriendGuesses){var f=this.player.fbFriendGuesses[d];"function"!=typeof f&&("undefined"==typeof b[f.r]&&(b[f.r]=0),b[f.r]+=1,c+=1)}d=[];for(var e in b)"function"!=typeof b[e]&&d.push(e);d.sort(function(a,c){return b[c]-b[a]});if(0<d.length&&(e=this.player.getResult(d[0])))this.dataFromServer={id:e.answererId};if(0==c&&this.properties.canSkip){zefJQuery(".zef_item_1").show();
zefJQuery(".zef_item_2").show();zefJQuery(".zef_item_3").show();zefJQuery(".zg_startInfoLoadIndicatorContainer").remove();return}}Zef.Component.prototype.buildVisual.call(this,a)};Zef.StartInfo.prototype.getGuessesForResult=function(a){var b=[];if(this.player.fbFriendGuesses)for(var c in this.player.fbFriendGuesses){var d=this.player.fbFriendGuesses[c];"function"!=typeof d&&d.r==a&&b.push(d)}return b};
Zef.StartInfo.prototype.loadFbFriendGuesses=function(a){var b=this;"undefined"!==typeof FB&&FB.api({method:"friends.get"},function(c){if(c){var d=0,f=Math.floor(c.length/20+1);if("undefined"===typeof b.player.fbFriendGuesses||null==b.player.fbFriendGuesses)b.player.fbFriendGuesses=[];for(var e=0;e<Math.floor(f);e++)Zef.queryDataServer("friendGuesses",{friends:c.slice(20*e,20*e+20)},function(c){d+=1;if(c)for(var e in c)"function"!=typeof c[e]&&b.player.fbFriendGuesses.push(c[e]);d==f&&a()},function(){d+=
1;d==f&&a()},function(){})}})};Zef.StartInfo.prototype.startInfoVisualDone=function(){zefJQuery(".zef_item_1").show();zefJQuery(".zef_item_2").show();zefJQuery(".zef_item_3").show()};Zef.AutoFBShare=function(){this.name="AutoFBShare";this.canShow=this.sharePerformed=!1};Zef.AutoFBShare.prototype=new Zef.Component;Zef.AutoFBShare.prototype.needsRebuildOnInputChange=function(){return!1};
Zef.AutoFBShare.prototype.buildUi=function(){if(!this.properties.shareAutomatically&&this.properties.performButton){"undefined"==typeof this.performButtonDiv&&(this.performButtonDiv=document.createElement("div"),this.performButtonDiv.setAttribute("class","zg_autoSharePerformButton"),this.performButtonDiv.innerHTML=this.properties.performButton);var a=this;this.player.buildDoneCb=function(){setTimeout(function(){zefJQuery(".questionListContent").append(zefJQuery(a.performButtonDiv));a.checkPerformButtonDivState()},
100)}}Zef.Component.prototype.buildUi.call(this)};
Zef.AutoFBShare.prototype.checkPerformButtonDivState=function(){if(this.performButtonDiv){var a=!0,b=this.player.components.get("ResultList").properties.threshold;if(b&&0<b)!1==this.player.components.get("ResultList").hasEnoughAnswers()&&(a=!1);else{var b=this.player.getQuestions(),c;for(c in b)"function"!=typeof b[c]&&!1===this.player.questionAnswered(b[c].id)&&(a=!1)}if(a){var d=this;zefJQuery(this.performButtonDiv).hasClass("zg_autoSharePerformButton")||zefJQuery(this.performButtonDiv).addClass("zg_autoSharePerformButton");
zefJQuery(this.performButtonDiv).hasClass("zg_autoSharePerformButtonDisabled")&&zefJQuery(this.performButtonDiv).removeClass("zg_autoSharePerformButtonDisabled");zefJQuery(this.performButtonDiv).unbind("click");zefJQuery(this.performButtonDiv).bind("click",function(){d.properties.shareButton?(d.canShow=!0,d.rebuildUi()):d.performShare()})}else zefJQuery(this.performButtonDiv).unbind("click"),zefJQuery(this.performButtonDiv).hasClass("zg_autoSharePerformButtonDisabled")||zefJQuery(this.performButtonDiv).addClass("zg_autoSharePerformButtonDisabled"),
zefJQuery(this.performButtonDiv).hasClass("zg_autoSharePerformButton")&&zefJQuery(this.performButtonDiv).removeClass("zg_autoSharePerformButton")}};
Zef.AutoFBShare.prototype.inputValueChanged=function(){if(!this.sharePerformed)if(this.properties.performButton&&(0==zefJQuery(".zg_autoSharePerformButton").length&&0==zefJQuery(".zg_autoSharePerformButtonDisabled").length)&&("undefined"==typeof this.performButtonDiv&&(this.performButtonDiv=document.createElement("div"),this.performButtonDiv.setAttribute("class","zg_autoSharePerformButton"),this.performButtonDiv.innerHTML=this.properties.performButton),zefJQuery(".questionListContent").append(zefJQuery(this.performButtonDiv)),
this.checkPerformButtonDivState()),this.properties.shareAutomatically){var a=this.player.components.get("ResultList").properties.threshold;if(a&&0<a){if(!1==this.player.components.get("ResultList").hasEnoughAnswers())return}else{var a=this.player.getQuestions(),b;for(b in a)if("function"!=typeof a[b]&&!1===this.player.questionAnswered(a[b].id))return}this.properties.shareButton?(this.canShow=!0,this.rebuildUi()):this.performShare()}else this.checkPerformButtonDivState()};
Zef.AutoFBShare.prototype.performShare=function(){this.properties.hidePlayer&&(zefJQuery(".zg_player_header").hide(),zefJQuery(".zef_item_1").hide(),zefJQuery(".zef_item_2").hide(),zefJQuery(".zef_item_3").hide(),zefJQuery(".zg_player_footer").hide());var a=this.player.getBestResult();if(!("undefined"===typeof a||null==a)){var b=this;if("undefined"==typeof this.player.fbFirstName&&"undefined"!==typeof FB)FB.api("/me",function(a){b.player.fbUserName=""+a.name;b.player.fbFirstName=""+a.first_name;b.player.fbLastName=
""+a.last_name;"undefined"==typeof b.player.fbFirstName&&("undefined"!=typeof b.player.fbLastName?b.player.fbFirstName=b.player.fbLastName:"undefined"!=typeof b.fbUserName&&(b.player.fbFirstName=b.player.fbUserName));"undefined"==typeof b.player.fbFirstName&&(b.player.fbFirstName="");b.performShare()}),this.player.fbFirstName="I am";else{if("undefined"==typeof this.player.fbFirstName||"undefined"==this.player.fbFirstName)this.player.fbFirstName="I am";var c=b.properties.title;if(b.shareLanguage&&
(Zef._locales&&Zef._locales[b.player.id])&&Zef._locales[b.player.id][b.shareLanguage]){var d=b.name+"_"+b.properties.id+"_title";Zef._locales[b.player.id][b.shareLanguage][d]&&(c=Zef._locales[b.player.id][b.shareLanguage][d])}var f=a.properties.name;b.shareLanguage&&(Zef._locales&&Zef._locales[b.player.id])&&Zef._locales[b.player.id][b.shareLanguage]&&(d="results_"+a.id+"_name",Zef._locales[b.player.id][b.shareLanguage][d]&&(f=Zef._locales[b.player.id][b.shareLanguage][d]));var c=c.replace(/{resultName}/g,
f),e=b.properties.name;b.shareLanguage&&(Zef._locales&&Zef._locales[b.player.id])&&Zef._locales[b.player.id][b.shareLanguage]&&(d=b.name+"_"+b.properties.id+"_name",Zef._locales[b.player.id][b.shareLanguage][d]&&(e=Zef._locales[b.player.id][b.shareLanguage][d]));var e=e.replace(/{resultName}/g,f),g=b.properties.description;if(a.properties.description){var h=a.properties.description;if(b.shareLanguage&&(Zef._locales&&Zef._locales[b.player.id])&&Zef._locales[b.player.id][b.shareLanguage]){var d=b.name+
"_"+b.properties.id+"_customProperties_description",j=b.name+"_"+b.properties.id+"_customProperties_Description";Zef._locales[b.player.id][b.shareLanguage][d]?h=Zef._locales[b.player.id][b.shareLanguage][d]:Zef._locales[b.player.id][b.shareLanguage][j]&&(h=Zef._locales[b.player.id][b.shareLanguage][j])}g=g.replace(/{resultDescription}/g,h)}g=g.replace(/{resultName}/g,f);e=e.replace(/{userName}/g,this.player.fbUserName);c=c.replace(/{userName}/g,this.player.fbUserName);g=g.replace(/{userName}/g,this.player.fbUserName);
e=e.replace(/{firstName}/g,this.player.fbFirstName);c=c.replace(/{firstName}/g,this.player.fbFirstName);g=g.replace(/{firstName}/g,this.player.fbFirstName);e=e.replace(/{lastName}/g,this.player.fbLastName);c=c.replace(/{lastName}/g,this.player.fbLastName);g=g.replace(/{lastName}/g,this.player.fbLastName);e=this.replaceResultFields(e,a);c=this.replaceResultFields(c,a);g=this.replaceResultFields(g,a);d="";b.properties.useImage&&(d=a.properties.targetImage,"undefined"!==typeof d&&(0>d.indexOf("//")&&
Zef._installLocation)&&(d=Zef._installLocation+d),"undefined"!==typeof d&&0==d.indexOf("//")&&(d="https:"+d));c={method:"feed",message:c,name:e,caption:c,description:g,link:b.player.properties.url,picture:d,ref:"autoshare"};b=this;"undefined"!==typeof FB&&(FB.ui(c,function(c){c&&c.post_id&&b.properties.ogaction&&FB.api("/me/"+b.properties.ogaction+"?"+b.properties.ogobject+"="+b.getResultProperty(b.properties.ogoid,a),"post",function(){})}),b.sharePerformed=!0);b.properties.nextComponent&&(b.hide(),
b.player.showComponent(b.properties.nextComponent))}}};
Zef.AutoFBShare.prototype.getResultProperty=function(a,b){var c="";if(a&&b.properties[a])c=b.properties[a];else if(a)for(var d in b.properties.customProperties)"function"!=typeof b.properties.customProperties[d]&&b.properties.customProperties[d].name==a&&(c=b.properties.customProperties[d].value);if(""==c)if(a&&b.properties[a.toLowerCase()])c=b.properties[a.toLowerCase()];else if(a)for(d in b.properties.customProperties)"function"!=typeof b.properties.customProperties[d]&&b.properties.customProperties[d].name.toLowerCase()==
a.toLowerCase()&&(c=b.properties.customProperties[d].value);return c};
Zef.AutoFBShare.prototype.replaceResultFields=function(a,b,c){var d=null;b.properties&&b.properties.customProperties?d=b.properties.customProperties:b.customProperties&&(d=b.customProperties);for(var f in d)if("function"!=typeof d[f]){var e=d[f];if(c){b=RegExp("{"+c+"."+e.name+"}","g");var g=e.value}else b=RegExp("{"+e.name+"}","g"),g=e.value;this.shareLanguage&&(Zef._locales&&Zef._locales[this.player.id])&&Zef._locales[this.player.id][this.shareLanguage]&&(e=this.name+"_"+this.properties.id+"_customProperties_"+
e.name,Zef._locales[this.player.id][this.shareLanguage][e]&&(g=Zef._locales[this.player.id][this.shareLanguage][e]));a=a.replace(b,g)}return a};Zef.FBCompare=function(){this.name="FBCompare";this.canShow=!1};Zef.FBCompare.prototype=new Zef.Component;Zef.FBCompare.prototype.needsRebuildOnInputChange=function(){return!1};
Zef.FBCompare.prototype.getFriendResult=function(a){var b=null;if(this.player.fbFriendResults)for(var c in this.player.fbFriendResults)if("function"!=typeof this.player.fbFriendResults[c]&&this.player.fbFriendResults[c].f==a){b=this.player.fbFriendResults[c].r;break}return b};
Zef.FBCompare.prototype.getFriendGuess=function(a){var b=null;if(this.player.fbFriendGuesses)for(var c in this.player.fbFriendGuesses)if("function"!=typeof this.player.fbFriendGuesses[c]&&this.player.fbFriendGuesses[c].f==a){b=this.player.fbFriendGuesses[c].r;break}return b};
Zef.FBCompare.prototype.loadFbFriendResults=function(a){var b=this;"undefined"!==typeof FB&&FB.api({method:"friends.get"},function(c){if(c){var d=0,f=c.length/20+1;if("undefined"===typeof b.player.fbFriendResults||null==b.player.fbFriendResults)b.player.fbFriendResults=[];for(var e=0;e<Math.floor(f);e++)Zef.queryDataServer("friendResults",{friends:c.slice(20*e,20*e+20)},function(c){d+=1;if(c)for(var e in c)"function"!=typeof c[e]&&b.player.fbFriendResults.push(c[e]);d==Math.floor(f)&&a()})}})};
Zef.FBCompare.prototype.loadFbFriendGuesses=function(a){if(!this.player.fbFriendGuesses){var b=this;"undefined"!==typeof FB&&FB.api({method:"friends.get"},function(c){if(c){var d=0,f=c.length/20+1;if("undefined"===typeof b.player.fbFriendGuesses||null==b.player.fbFriendGuesses)b.player.fbFriendGuesses=[];for(var e=0;e<Math.floor(f);e++)Zef.queryDataServer("friendGuesses",{friends:c.slice(20*e,20*e+20)},function(c){d+=1;if(c)for(var e in c)"function"!=typeof c[e]&&b.player.fbFriendGuesses.push(c[e]);
d==Math.floor(f)&&a()})}})}};Zef.FBCompare.prototype.getMyGuess=function(a){var b=null;if(this.player.myGuesses)for(var c in this.player.myGuesses)if("function"!=typeof this.player.myGuesses[c]&&this.player.myGuesses[c].f==a){b=this.player.myGuesses[c].r;break}return b};
Zef.FBCompare.prototype.addMyGuess=function(a){if("undefined"===typeof this.player.myGuesses||null==this.player.myGuesses)this.player.myGuesses=[];var b=!1,c;for(c in this.player.myGuesses)this.player.myGuesses[c].f==a.f&&(this.player.myGuesses[c].r=a.r,b=!0);!1==b&&this.player.myGuesses.push(a)};
Zef.FBCompare.prototype.loadMyGuesses=function(a){var b=this;"undefined"!==typeof FB&&FB.api({method:"friends.get"},function(c){if(c){var d=0,f=c.length/20+1;if("undefined"===typeof b.player.myGuesses||null==b.player.myGuesses)b.player.myGuesses=[];for(var e=0;e<Math.floor(f);e++)Zef.queryDataServer("myGuesses",{friends:c.slice(20*e,20*e+20)},function(c){d+=1;if(c)for(var e in c)"function"!=typeof c[e]&&b.addMyGuess(c[e]);d==Math.floor(f)&&a()})}})};
Zef.FBCompare.prototype.hasAnswer=function(a){return null!=this.getFriendResult(a)};Zef.FBChallenge=function(){this.name="FBChallenge";this.canShow=!1};Zef.FBChallenge.prototype=new Zef.FBCompare;Zef.FBChallenge.prototype.needsRebuildOnInputChange=function(){return!1};Zef.FBChallenge.prototype.getResult=function(){return"undefined"===typeof this.result||null==this.result?this.player.getBestResult():this.result};
Zef.FBChallenge.prototype.setResult=function(a){a.properties?this.result=a:(this.result={properties:a,id:a.answererId},this.result.properties.id=this.result.id);this.disableAnswered=!0};Zef.GuessRewards=function(){this.name="GuessRewards";this.canShow=!1};Zef.GuessRewards.prototype=new Zef.Component;
Zef.GuessRewards.prototype.show=function(){var a=this;"undefined"==typeof this.player.myGuesses||null==this.player.myGuesses?this.loadMyGuesses(function(){a.show()}):this.loadUnclaimedGuesses(function(b){b&&0<b.length?(a.correctGuesses=b,a.canShow=!0,a.rebuildUi()):a.properties.noGuesses&&0<a.player.myGuesses.length?(a.noResults=!0,a.canShow=!0,a.rebuildUi()):a.properties.skipIfNoRewards&&a.properties.skipToComponent&&(a.hide(),a.player.showComponent(a.properties.skipToComponent))})};
Zef.GuessRewards.prototype.addMyGuess=function(a){if("undefined"===typeof this.player.myGuesses||null==this.player.myGuesses)this.player.myGuesses=[];var b=!1,c;for(c in this.player.myGuesses)this.player.myGuesses[c].f==a.f&&(this.player.myGuesses[c].r=a.r,b=!0);!1==b&&this.player.myGuesses.push(a)};
Zef.GuessRewards.prototype.loadMyGuesses=function(a){var b=this;"undefined"!==typeof FB&&FB.api({method:"friends.get"},function(c){if("undefined"===typeof b.player.myGuesses||null==b.player.myGuesses)b.player.myGuesses=[];if(c)for(var d=0,f=c.length/20+1,e=0;e<Math.floor(f);e++)Zef.queryDataServer("myGuesses",{friends:c.slice(20*e,20*e+20)},function(c){d+=1;if(c)for(var e in c)"function"!=typeof c[e]&&b.addMyGuess(c[e]);d==Math.floor(f)&&a()})})};
Zef.GuessRewards.prototype.loadUnclaimedGuesses=function(a){var b=this;"undefined"==typeof this.guesses||null==this.guesses?"undefined"!==typeof FB&&FB.api({method:"friends.get"},function(c){if(c)for(var d=0,f=c.length/20+1,e=[],g=0;g<Math.floor(f);g++)Zef.queryDataServer("getUnclaimed",{friends:c.slice(20*g,20*g+20)},function(c){d+=1;if(c)for(var g in c)"function"!=typeof c[g]&&e.push(c[g]);d==Math.floor(f)&&(b.guesses=e,a(b.guesses))})}):a(this.guesses)};
Zef.ExternalResultSave=function(){this.name="ExternalResultSave"};Zef.ExternalResultSave.prototype=new Zef.Component;Zef.ExternalResultSave.prototype.needsRebuildOnInputChange=function(){return!1};
Zef.ExternalResultSave.prototype.inputValueChanged=function(a,b,c){if(this.properties.saveReplies){var d=!1;this.properties.skipSliders&&c&&"line1d"==c.name&&(d=!0);!1==d&&this.saveToServer("saveReply",{q:a,v:b})}if(this.properties.atEnd)if((a=this.player.components.get("ResultList").properties.threshold)&&0<a){if(!1==this.player.components.get("ResultList").hasEnoughAnswers())return}else{a=this.player.getQuestions();for(var f in a)if("function"!=typeof a[f]&&!1===this.player.questionAnswered(a[f].id))return}f=
this.player.getBestResult();"undefined"===typeof f||null==f||this.saveToServer("result",{result:f.id})};
Zef.ExternalResultSave.prototype.saveToServer=function(a,b,c,d,f){"undefined"!==typeof Zef._params&&null!=Zef._params&&(b.ep=Zef._params,"undefined"!==typeof Zef._answerer&&(b.ak=Zef._answerer));if(Zef._zefPlayer&&Zef._zefPlayer.tags)for(var e in Zef._zefPlayer.tags)if("string"==typeof Zef._zefPlayer.tags[e]&&0==Zef._zefPlayer.tags[e].indexOf("fbid=")){b.fbid=Zef._zefPlayer.tags[e].substring(5);if("undefined"==typeof b||null==b)b={};break}e=this.properties.url;if("undefined"==typeof e||null==e||""==
e)e=Zef._dataServer;zefJQuery.ajax({url:e+"?zefid="+Zef._zefId+"&op="+a+"&playerId="+Zef._playerId+"&lang="+Zef._lang,data:b,success:c,error:d,dataType:"jsonp",complete:f,traditional:!0})};Zef.AllResults=function(){this.name="AllResults";this.canShow=!1};Zef.AllResults.prototype=new Zef.Component;Zef.AllResults.prototype.needsRebuildOnInputChange=function(){return!1};Zef.ResultInfo=function(){this.name="ResultInfo";this.canShow=!1;this.result=null};Zef.ResultInfo.prototype=new Zef.Component;
Zef.ResultInfo.prototype.needsRebuildOnInputChange=function(){return!1};Zef.ResultInfo.prototype.setResult=function(a){this.result=a};Zef.LanguageSelector=function(){this.name="LanguageSelector"};Zef.LanguageSelector.prototype=new Zef.Component;Zef.LanguageSelector.prototype.needsRebuildOnInputChange=function(){return!1};
Zef.LanguageSelector.prototype.buildVisual=function(a){Zef._zefPlayer.languageSelected||(this.properties.defaultLang&&"undefined"==typeof Zef._zefPlayer.defaultSelected&&(Zef._lang=this.properties.defaultLang,Zef._zefPlayer.defaultSelected=!0,Zef._zefPlayer.reapplyI18n()),Zef.Component.prototype.buildVisual.call(this,a))};Zef.LanguageSelector.prototype.applyChange=function(){Zef._zefPlayer.languageSelected=!0;Zef._zefPlayer.hide();Zef._zefPlayer.reapplyI18n();Zef._zefPlayer.show()};
Zef.NotifyCorrectGuesses=function(){this.name="NotifyCorrectGuesses";this.notifyPerformed=!1};Zef.NotifyCorrectGuesses.prototype=new Zef.Component;Zef.NotifyCorrectGuesses.prototype.needsRebuildOnInputChange=function(){return!1};
Zef.NotifyCorrectGuesses.prototype.inputValueChanged=function(){if(!this.notifyPerformed){var a=this.player.components.get("ResultList").properties.threshold;if(a&&0<a){var b=this.player.getQuestions(),c=0,d;for(d in b)"function"!=typeof b[d]&&!0===this.player.questionAnswered(b[d].id)&&(c+=1);if(c<a)return}else for(d in b=this.player.getQuestions(),b)if("function"!=typeof b[d]&&!1===this.player.questionAnswered(b[d].id))return;var f=this;this.loadFbFriendGuesses(function(){f.performNotify()})}};
Zef.NotifyCorrectGuesses.prototype.addFriendGuess=function(a){var b=!0,c;for(c in this.player.fbFriendGuesses)"function"!=typeof this.player.fbFriendGuesses[c]&&this.player.fbFriendGuesses[c].f==a.f&&(this.player.fbFriendGuesses[c].r=a.r,b=!1);b&&this.player.fbFriendGuesses.push(a)};
Zef.NotifyCorrectGuesses.prototype.loadFbFriendGuesses=function(a){var b=this;"undefined"!==typeof FB&&FB.api({method:"friends.get"},function(c){if(c){var d=0,f=c.length/20+1;if("undefined"===typeof b.player.fbFriendGuesses||null==b.player.fbFriendGuesses)b.player.fbFriendGuesses=[];for(var e=0;e<Math.floor(f);e++)Zef.queryDataServer("friendGuesses",{friends:c.slice(20*e,20*e+20)},function(c){d+=1;if(c)for(var e in c)"function"!=typeof c[e]&&b.addFriendGuess(c[e]);d==Math.floor(f)&&a()})}})};
Zef.NotifyCorrectGuesses.prototype.isToday=function(a){var b=a.slice(0,-5).split(/\D/).map(function(a){return parseInt(a,10)||0});b[1]-=1;b=new Date(Date.UTC.apply(Date,b));a=a.slice(-5);var c=parseInt(a,10)/100;"+"==a.slice(0,1)&&(c*=-1);b.setHours(b.getHours()+c);a=new Date;a.setHours(0);a.setMinutes(0);a.setSeconds(0);return b.getTime()>=a.getTime()};
Zef.NotifyCorrectGuesses.prototype.notifyUser=function(a){var b=this;FB.api("/"+a+"/apprequests",function(c){var d=!0;if(0<c.length)for(var f in c)"function"!=typeof c[f]&&b.isToday(c[f].created_time)&&(d=!1);d&&FB.api("/"+a,function(c){var d=Zef._lang;c.locale&&(d=c.locale.substring(0,2));c=b.properties.text;if(d&&(Zef._locales&&Zef._locales[b.player.id])&&Zef._locales[b.player.id][d]){var f=b.name+"_"+b.properties.id+"_subtitle";Zef._locales[b.player.id][d][f]&&(c=Zef._locales[b.player.id][d][f])}Zef.queryDataServer("notify",
{to:a,txt:c},function(){})});Zef.queryDataServer("appreq",{to:a,txt:b.properties.text},function(){})})};Zef.NotifyCorrectGuesses.prototype.performNotify=function(){var a=this.player.getBestResult();if(!("undefined"===typeof a||null==a)){var b=[],c;for(c in this.player.fbFriendGuesses)"function"!=typeof this.player.fbFriendGuesses[c]&&a.id==this.player.fbFriendGuesses[c].r&&b.push(this.player.fbFriendGuesses[c].f);for(var d in b)"function"!=typeof b[d]&&this.notifyUser(b[d]);this.notifyPerformed=!0}};