Array.prototype.indexOf||(Array.prototype.indexOf=function(a,b){for(var c=b||0,d=this.length;c<d;c++)if(this[c]===a)return c;return-1});function Map(a){this.current=void 0;this.size=0;this.isLinked=!0;!1===a&&this.disableLinking()}Map.from=function(a,b,c){c=new Map(c);for(var d in a)(b||a.hasOwnProperty(d))&&c.put(d,a[d]);return c};Map.noop=function(){return this};Map.illegal=function(){throw Error("can't do this with unlinked maps");};
Map.prototype.disableLinking=function(){this.isLinked=!1;this.disableLinking=this.unlink=this.link=Map.noop;this.listValues=this.listKeys=this.drop=this.flip=this.each=this.removeAll=this.value=this.key=this.next=Map.illegal;return this};Map.prototype.hash=function(a){return a instanceof Object?a.__hash||(a.__hash="object "+ ++arguments.callee.current):typeof a+" "+String(a)};Map.prototype.hash.current=0;
Map.prototype.link=function(a){0===this.size?(a.prev=a,this.current=a.next=a):(a.prev=this.current.prev,a.prev.next=a,a.next=this.current,this.current.prev=a)};Map.prototype.unlink=function(a){0===this.size?this.current=void 0:(a.prev.next=a.next,a.next.prev=a.prev,a===this.current&&(this.current=a.next))};Map.prototype.get=function(a){a=this[this.hash(a)];return"undefined"===typeof a?void 0:a.value};
Map.prototype.put=function(a,b){var c=this.hash(a);if(this.hasOwnProperty(c))this[c].value=b;else{var d={key:a,value:b};this[c]=d;this.link(d);++this.size}return this};Map.prototype.remove=function(a){a=this.hash(a);this.hasOwnProperty(a)&&(--this.size,this.unlink(this[a]),delete this[a]);return this};Map.prototype.removeAll=function(){for(;this.size;)this.remove(this.key());return this};Map.prototype.contains=function(a){return this.hasOwnProperty(this.hash(a))};
Map.prototype.isUndefined=function(a){a=this.hash(a);return this.hasOwnProperty(a)?"undefined"===typeof this[a]:!1};Map.prototype.next=function(){this.current=this.current.next};Map.prototype.key=function(){return this.current.key};Map.prototype.value=function(){return this.current.value};Map.prototype.each=function(a,b){"undefined"===typeof b&&(b=this);for(var c=this.size;c--;this.next()){var d=a.call(b,this.key(),this.value(),0<c);"number"===typeof d&&(c+=d)}return this};
Map.prototype.flip=function(a){a=new Map(a);for(var b=this.size;b--;this.next()){var c=this.value(),d=a.get(c);d?d.push(this.key()):a.put(c,[this.key()])}return a};Map.prototype.drop=function(a,b){"undefined"===typeof b&&(b=this);for(var c=this.size;c--;)a.call(b,this.key(),this.value())?(this.remove(this.key()),--c):this.next();return this};Map.prototype.listValues=function(){for(var a=[],b=this.size;b--;this.next())a.push(this.value());return a};
Map.prototype.listKeys=function(){for(var a=[],b=this.size;b--;this.next())a.push(this.key());return a};Map.prototype.toString=function(){function a(a,d,e){b+="    { "+this.hash(a)+" : "+d+" }"+(e?",":"")+"\n"}var b="[object Map";this.isLinked&&this.size&&(b+="\n",this.each(a));return b+="]"};Map.reverseIndexTableFrom=function(a,b){for(var c=new Map(b),d=0,e=a.length;d<e;++d){var f=a[d],g=c.get(f);g?g.push(d):c.put(f,[d])}return c};
Map.cross=function(a,b,c,d){var e,f;a.isLinked?(e=a,f=b):b.isLinked?(e=b,f=a):Map.illegal();for(var g=e.size;g--;e.next()){var h=e.key();f.contains(h)&&c.call(d,h,a.get(h),b.get(h))}return d};Map.uniqueArray=function(a){for(var b=new Map,c=0,d=a.length;c<d;++c)b.put(a[c]);return b.listKeys()};
zefJQuery.fn.sortElements=function(){var a=[].sort;return function(b,c){c=c||function(){return this};var d=this.map(function(){var a=c.call(this),b=a.parentNode,d=b.insertBefore(document.createTextNode(""),a.nextSibling);return function(){if(b===this)throw Error("You can't sort elements if any one is a descendant of another.");b.insertBefore(this,d);b.removeChild(d)}});return a.call(this,b).each(function(a){d[a].call(c.call(this))})}}();var Zef=window.Zef||{};
Zef.queryDataServer=function(a,b,c,d,e){"undefined"!==typeof Zef._params&&null!=Zef._params&&(b.ep=Zef._params,"undefined"!==typeof Zef._answerer&&(b.ak=Zef._answerer));if(Zef._zefPlayer&&Zef._zefPlayer.tags)for(var f in Zef._zefPlayer.tags)if("string"==typeof Zef._zefPlayer.tags[f]&&0==Zef._zefPlayer.tags[f].indexOf("fbid=")){b.fbid=Zef._zefPlayer.tags[f].substring(5);if("undefined"==typeof b||null==b)b={};break}zefJQuery.ajax({url:Zef._dataServer+"?zefid="+Zef._zefId+"&op="+a+"&playerId="+Zef._playerId+
"&lang="+Zef._lang,data:b,success:c,error:d,dataType:"jsonp",complete:e,traditional:!0,timeout:3E4})};Zef.loadFromServer=function(a,b,c,d,e){if("undefined"!==typeof Zef._params&&null!=Zef._params){if("undefined"==typeof b||null==b)b={};b.ep=Zef._params;"undefined"!==typeof Zef._answerer&&(b.ak=Zef._answerer)}zefJQuery.ajax({url:Zef._host+Zef._servlet+"?zefid="+Zef._zefId+"&op="+a+"&playerId="+Zef._playerId+"&lang="+Zef._lang,data:b,success:c,error:d,dataType:"jsonp",complete:e})};
Zef.loadFromServerSync=function(a,b,c,d,e){if("undefined"!==typeof Zef._params&&null!=Zef._params){if("undefined"==typeof b||null==b)b={};b.ep=Zef._params;"undefined"!==typeof Zef._answerer&&(b.ak=Zef._answerer)}zefJQuery.ajax({url:Zef._host+Zef._servlet+"?zefid="+Zef._zefId+"&op="+a+"&playerId="+Zef._playerId+"&lang="+Zef._lang,data:b,success:c,error:d,dataType:"jsonp",complete:e,async:!1})};
Zef.loadFromServerNoAjax=function(a,b,c,d,e){if("undefined"!==typeof Zef._params&&null!=Zef._params){if("undefined"==typeof b||null==b)b={};b.ep=Zef._params;"undefined"!==typeof Zef._answerer&&(b.ak=Zef._answerer)}zefJQuery.ajax({url:Zef._host+Zef._servlet+"?zefid="+Zef._zefId+"&op="+a+"&playerId="+Zef._playerId+"&lang="+Zef._lang,data:b,dataType:"json",success:c,error:d,complete:e})};Zef.log=function(a){Zef._debug&&"undefined"!==typeof console&&console.log(a)};Zef.loadedHtmlComponents={};
Zef.loadedHtmlComponentStatuses={};Zef.prepareComponentHtml=function(a,b){a[b]=a[b].substring(4,a[b].length-3);var c=a[b].indexOf("<body>");0<=c&&(c+=6);var d=a[b].indexOf("</body>");0>d&&(d=a[b].length);a[b].substring(0,c);a[b]=a[b].substring(c,d)};
Zef.loadHtml=function(a,b,c){if("undefined"!==typeof Zef._inGStorage&&0>a.htmlSrc.indexOf("http")&&0>a.htmlSrc.indexOf("//")||"undefined"!==typeof Zef._inZip&&!0===Zef._inZip){var d=a.htmlSrc;if(("undefined"===Zef._inZip||!1===Zef._inZip)&&"/zefglobal"!==d.substring(0,10))d="/zefglobal/common"+d;Zef.loadCss(a,b,function(){zefJQuery.get(d,function(a){b.html=a;Zef.prepareComponentHtml(b,"html");c()})})}else Zef.loadCss(a,b,function(){Zef.loadFromServerNoAjax("loadHtmlSource",{addr:a.htmlSrc},function(a){b.html=
a.source;Zef.prepareComponentHtml(b,"html");c()},function(){})})};
Zef.loadCss=function(a,b,c){if("undefined"!==typeof a.cssSrc){var d=a.cssSrc;if("undefined"!==typeof Zef._inGStorage&&0>d.indexOf("http")&&0>d.indexOf("//")||"undefined"!==typeof Zef._inZip&&!0===Zef._inZip){if(("undefined"===Zef._inZip||!1===Zef._inZip)&&"/zefglobal"!==d.substring(0,10))d="/zefglobal/common"+d}else 0<=a.cssSrc.indexOf("blob:")&&(d=Zef._host+"cssloader?key="+a.cssSrc.substring(5));if("undefined"!==typeof document.createStyleSheet)document.createStyleSheet(d);else{var e=zefJQuery("<link>");
e.attr({rel:"stylesheet",type:"text/css",href:d});zefJQuery("head").append(e)}}"undefined"!==typeof a.groupHtmlSrc?Zef.loadFromServerNoAjax("loadHtmlSource",{addr:a.groupHtmlSrc},function(d){b.groupHtml=d.source;Zef.prepareComponentHtml(b,"groupHtml");Zef.loadGroupCss(a,b,c)},function(){}):c()};
Zef.loadGroupCss=function(a,b,c){"undefined"!==typeof a.groupCssSrc&&("undefined"!==typeof document.createStyleSheet?document.createStyleSheet(a.groupCssSrc):(b=zefJQuery("<link>"),b.attr({rel:"stylesheet",type:"text/css",href:a.groupCssSrc}),zefJQuery("head").append(b)));c()};Zef._ZefUiComponentCallQueue=[];
Zef.executeUiComponentCallQueue=function(){var a=Zef._ZefUiComponentCallQueue;Zef._ZefUiComponentCallQueue=[];a.length&&zefJQuery.each(a,function(){this[0][this[1]](this[2],this[3])});a=[];this.uiDone=!0};Zef.getQuestionRelativeValue=function(a,b,c,d,e){var f=b;c&&(f=d+(e-d)*((b-a.props.minimumValue)/(a.props.maximumValue-a.props.minimumValue)));return f};